# Common settings for all

# This identifies all of the resources as belonging to this particular chart,
# even though they will ultimately be named likely by the parent chart that
# uses this as a dependency.
chart_name: prometheus-rules
chart_source: https://github.com/Nextdoor/k8s-public-charts
runbook_url: https://github.com/Nextdoor/k8s-public-charts/tree/main/charts/prometheus-rules/runbook.md

#
#
