{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "iam-manager.fullname" . }}-servingcert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iam-manager.labels" . | nindent 4 }}
spec:
  commonName: {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}
  dnsNames:
  - {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}
  - {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: iam-manager-selfsigned-issuer
    name: {{ include "iam-manager.fullname" . }}-selfsigned-issuer
  secretName: {{ include "iam-manager.fullname" . }}-webhook-server-cert
{{- end }}
