{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "iam-manager.fullname" . }}-serving-cert
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iam-manager.labels" . | nindent 4 }}
spec:
  commonName: {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Values.namespace }}
  dnsNames:
  - {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Values.namespace }}
  - {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Values.namespace }}.svc
  - {{ include "iam-manager.fullname" . }}-webhook-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: iam-manager-selfsigned-issuer
    name: {{ include "iam-manager.fullname" . }}-selfsigned-issuer
  secretName: {{ include "iam-manager.fullname" . }}-webhook-server-cert
{{- end }}
