apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iam-manager.labels" . | nindent 4 }}
data:
  {{- $global := . }}
  {{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ tpl $v $global }}
  {{- end }}
