apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "iam-manager.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iam-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "iam-manager.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "iam-manager.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
