apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "iam-manager.fullname" . }}-webhook-ingress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "iam-manager.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - ports:
        - port: 9443
          protocol: TCP
