{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "iam-manager.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "iam-manager.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: iam-manager-system/iam-manager-serving-cert
webhooks:
- name: viamrole.kb.io
  admissionReviewVersions: [ v1, v1beta1 ]
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "iam-manager.fullname" . }}-webhook-service
      namespace: {{ .Values.namespace }}
      path: /validate-iammanager-keikoproj-io-v1alpha1-iamrole
  failurePolicy: Fail
  sideEffects: None
  rules:
  - apiGroups:
    - iammanager.keikoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iamroles
{{- end }}
